# Generated by Django 4.1.2 on 2022-10-26 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=25)),
                ('house', models.CharField(max_length=10)),
                ('post_code', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mins',
            fields=[
                ('id_min', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('origin', models.CharField(max_length=50)),
                ('definition', models.CharField(blank=True, max_length=255, null=True)),
                ('available', models.IntegerField()),
                ('size', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'mins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('e_mail', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.ForeignKey(db_column='address_id', on_delete=django.db.models.deletion.DO_NOTHING, to='bmstu_lab.address')),
            ],
            options={
                'db_table': 'customer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reserve_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='bmstu_lab.customer')),
                ('id_min', models.ForeignKey(db_column='id_min', on_delete=django.db.models.deletion.DO_NOTHING, to='bmstu_lab.mins')),
            ],
            options={
                'db_table': 'reservation',
                'managed': True,
            },
        ),
    ]
